FROM python:3.7-slim-buster

#RUN apt-get update \
#    && apt-get install git -y --no-install-recommends

#COPY src src/
COPY . /

RUN pip install -r requirements.txt
#RUN git clone https://gitlab.int.aisingapore.org/aims/federatedlearning/synergos_archive \
#    && pip install ./synergos_archive

RUN pip install ./synergos_archive

EXPOSE 12345

CMD ["python", "-m", "src.app"]
