##############
# Base Image #
##############

FROM python:3.7-slim-buster as base

COPY . /

RUN pip install -r requirements.txt

RUN pip install ./synergos_archive

EXPOSE 12345

CMD ["python", "-m", "src.app"]
