version: '3'


services:
  
  synui_track:
    build:
      context: ./synui_track
      dockerfile: Dockerfile_track
    image: synergos_ui:track
    ports:
      - "${SYNUI_TRACK_PORT}:4000"
    # networks:
    #   - synergos
    network_mode: bridge


  synui_view:
    build:
      context: .
      dockerfile: ./synui_view/Dockerfile_view
    image: synergos_ui:view
    environment:
      - TRACK_HOST=${SYNUI_TRACK_HOST:-localhost}
      - TRACK_PORT=${SYNUI_TRACK_PORT}
    ports:
      - "${SYNUI_VIEW_PORT}:4000"
    depends_on: 
      - synui_track
    # networks:
    #   - synergos
    network_mode: bridge

  synui_nav:
    build:
      context: ./synui_nav
      dockerfile: Dockerfile_nav
    image: synergos_ui:nav
    environment:
      - VIEW_HOST=${SYNUI_VIEW_HOST:-localhost}
      - VIEW_PORT=${SYNUI_VIEW_PORT}
    ports:
      - "${SYNUI_NAV_PORT}:4000"
    depends_on: 
      - synui_view
    # networks:
    #   - synergos
    network_mode: bridge

# networks:
#   synergos:
