FROM node:12.22-buster-slim

RUN apt-get update \
    && apt-get install -y git

RUN git clone https://github.com/neo4j/neo4j-browser.git

WORKDIR /neo4j-browser
RUN git checkout release-4.2.5

RUN yarn install

EXPOSE 8080

CMD ["yarn", "start"]
