version: '3'


services:
  
  synui_view:
    build:
      context: .
      dockerfile: ./setup/Dockerfile_view
    image: synergos_ui:view
    ports:
      - "3000"

  synui_nav:
    build:
      context: .
      dockerfile: ./setup/Dockerfile_nav
    image: synergos_ui:nav
    ports:
      - "3000:3000"
    depends_on: 
    - synui_view
