version: "3.9"
services:
  web:
    build:
      context: nginx_docker
      dockerfile: 'Dockerfile.dev'
    image: ui-web
    container_name: ui-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - webapp
  webapp:
    build:
      context: synergos_ui
      dockerfile: 'Dockerfile.dev'
    image: ui-vue
    container_name: ui-vue
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - nav
  nav:
    build:
      context: synergos_ui_nav
      dockerfile: 'Dockerfile.dev'
    image: ui-nav
    container_name: ui-nav
    restart: always
    ports:
      - "12345:12345"

