##############
# Base Image #
##############

FROM node:12.22-buster-slim as base

RUN apt-get update \
 && apt-get install -y git systemd

RUN git clone https://github.com/neo4j/neo4j-browser.git

WORKDIR /neo4j-browser
RUN git checkout release-4.2.5

RUN yarn install

EXPOSE 8080

# ###########################
# # Implementation Footnote #
# ###########################

# # [Cause]
# # Linux uses the inotify package to observe filesystem events, individual files
# # or directories, monitoring them for changes. Since React/Angular/Vue 
# # hot-reloads and recompiles files on save it needs to keep track of all 
# # project's files. It is hence not uncommon to encounter a system limit on the 
# # number of files you can monitor. For example, Ubuntu Lucid's (64bit) inotify 
# # limit is set to 8192.

# # [Problems]
# # The number of files monitored by the system will eventually reach the limit,
# # resulting in "Error: ENOSPC: System limit for number of file watchers 
# # reached, ..."

# # [Solution]
# # Increasing the amount of inotify watchers should hide the warning messages.
# # https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached

# # insert the new value into the system config
# RUN echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf
# ENTRYPOINT ["sysctl", "-p"]

CMD ["yarn", "start"]
