##############
# Base Image #
##############

FROM nginx:1.19.9 as base

# Remove default Nginx config
RUN rm /etc/nginx/nginx.conf

# Copy the modified Nginx conf
COPY nginx.conf /etc/nginx

EXPOSE 80
